// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxoxxW8WBjpUi6hUL4Ne1rqbX1cH12WvE',
    appId: '1:910310235404:web:ab6eeeabc69739510a7d29',
    messagingSenderId: '910310235404',
    projectId: 'salao-de-cabelo-3b6f7',
    authDomain: 'salao-de-cabelo-3b6f7.firebaseapp.com',
    storageBucket: 'salao-de-cabelo-3b6f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjCUsju_jcE0ZMuqLhGTl-7kknLipv-pY',
    appId: '1:910310235404:android:88982e824fa5e8fa0a7d29',
    messagingSenderId: '910310235404',
    projectId: 'salao-de-cabelo-3b6f7',
    storageBucket: 'salao-de-cabelo-3b6f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEAtatuQ4ysjdesZWf6FnJUITl4JRs2Bo',
    appId: '1:910310235404:ios:1868a44fd6dfef5e0a7d29',
    messagingSenderId: '910310235404',
    projectId: 'salao-de-cabelo-3b6f7',
    storageBucket: 'salao-de-cabelo-3b6f7.firebasestorage.app',
    iosBundleId: 'com.example.salaoDeCabelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEAtatuQ4ysjdesZWf6FnJUITl4JRs2Bo',
    appId: '1:910310235404:ios:1868a44fd6dfef5e0a7d29',
    messagingSenderId: '910310235404',
    projectId: 'salao-de-cabelo-3b6f7',
    storageBucket: 'salao-de-cabelo-3b6f7.firebasestorage.app',
    iosBundleId: 'com.example.salaoDeCabelo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxoxxW8WBjpUi6hUL4Ne1rqbX1cH12WvE',
    appId: '1:910310235404:web:aaa8131a309dc34e0a7d29',
    messagingSenderId: '910310235404',
    projectId: 'salao-de-cabelo-3b6f7',
    authDomain: 'salao-de-cabelo-3b6f7.firebaseapp.com',
    storageBucket: 'salao-de-cabelo-3b6f7.firebasestorage.app',
  );
}
